import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { toast } from "react-toastify";
import Sidebar from "../components/Sidebar";
import loadCategories from "../lib/loadCategories";
import { ICategory, IItem, ITag } from "../types/types";
import Navbar from "../components/Navbar";
import { GetStaticProps } from "next";
import loadItems from "../lib/loadItems";
import Banner from "../components/Banner";
import Card from "../components/Card";
import Testimonials from "../components/Testimonials";
import Link from "next/link";
import Footer from "../components/Footer";
import fetcher from "../lib/fetcher";

interface HomeProps {
  categories: ICategory[];
  items: IItem[];
  tags: ITag[];
}

export default function Home({ categories, items, tags }: HomeProps) {
  const notify = () => toast("Wow so easy!");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar categories={categories} />
      <div className={styles.container}>
        <Sidebar
          categories={categories.slice(0, 5)}
          items={items.slice(0, 5)}
        />
        <section className={styles.content}>
          <div className={styles.banners}>
            <Banner
              title="Banner subfocus"
              heading="Space for heading"
              link={{ href: "/", title: "Read recepies" }}
              backgroundImage="https://image.shutterstock.com/image-photo/old-brick-black-color-wall-260nw-1605128917.jpg"
            />
            <Banner
              title="Banner subfocus"
              heading="Space for heading"
              link={{ href: "/", title: "Read recepies" }}
            />
          </div>
          <div className={styles.cards}>
            {items.slice(0, 6).map((item) => (
              <Card key={item.id} item={item} />
            ))}
          </div>
        </section>
      </div>

      <Testimonials />

      <Footer tags={tags} />
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const categories = await loadCategories();
  const items = await loadItems({ limit: 6 });
  const tags = await fetcher("/api/tags/");

  return {
    props: { categories, items, tags },
    revalidate: 10,
  };
};
