import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { toast } from "react-toastify";
import Sidebar from "../components/Sidebar";
import loadCategories from "../lib/loadCategories";
import { ICategory, IItem } from "../types";
import Navbar from "../components/Navbar";
import { GetStaticProps } from "next";
import loadItems from "../lib/loadItems";
import Banner from "../components/Banner";
import Card from "../components/Card";

interface HomeProps {
  categories: ICategory[];
  items: IItem[];
}

export default function Home({ categories, items }: HomeProps) {
  const notify = () => toast("Wow so easy!");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar categories={categories} />
      <div className={styles.container}>
        <Sidebar
          categories={categories.slice(0, 5)}
          items={items.slice(0, 5)}
        />
        <section className={styles.content}>
          <div className={styles.banners}>
            <Banner
              title="Banner subfocus"
              heading="Space for heading"
              link={{ href: "/", title: "Read recepies" }}
              backgroundImage="https://image.shutterstock.com/image-photo/old-brick-black-color-wall-260nw-1605128917.jpg"
            />
            <Banner
              title="Banner subfocus"
              heading="Space for heading"
              link={{ href: "/", title: "Read recepies" }}
            />
          </div>
          <div className={styles.cards}>
            <Card />
          </div>
        </section>
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const categories = await loadCategories();
  const items = await loadItems();

  return {
    props: { categories, items },
    revalidate: 10,
  };
};
